// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecResServer.Model;

namespace SecResServer.Migrations
{
    [DbContext(typeof(SecResDbContext))]
    [Migration("20190526031212_EdgarCompanyUpdateDT")]
    partial class EdgarCompanyUpdateDT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SecResServer.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SecResServer.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SecResServer.Model.EdgarCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cik");

                    b.Property<int>("EntityId");

                    b.Property<DateTime>("LastUpdateDT");

                    b.Property<string>("MarketOperator");

                    b.Property<string>("Markettier");

                    b.Property<string>("Name");

                    b.Property<string>("PrimaryExchange");

                    b.Property<string>("PrimarySymbol");

                    b.Property<int>("SicCode");

                    b.Property<string>("SicDescription");

                    b.HasKey("Id");

                    b.ToTable("EdgarCompanies");
                });

            modelBuilder.Entity("SecResServer.Model.Company", b =>
                {
                    b.HasOne("SecResServer.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
